//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szakdolgozat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szakdolgozat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm_Event.
        /// </summary>
        internal static string AlarmEvent {
            get {
                return ResourceManager.GetString("AlarmEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice Blue.
        /// </summary>
        internal static string AliceBlue {
            get {
                return ResourceManager.GetString("AliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F0F8FF.
        /// </summary>
        internal static string AliceBlueHexValue {
            get {
                return ResourceManager.GetString("AliceBlueHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        internal static string BlackHexValue {
            get {
                return ResourceManager.GetString("BlackHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0000FF.
        /// </summary>
        internal static string BlueHexValue {
            get {
                return ResourceManager.GetString("BlueHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A52A2A.
        /// </summary>
        internal static string BrownHexValue {
            get {
                return ResourceManager.GetString("BrownHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed_Event.
        /// </summary>
        internal static string ChangedEvent {
            get {
                return ResourceManager.GetString("ChangedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionError_Event.
        /// </summary>
        internal static string ConnectionErrorEvent {
            get {
                return ResourceManager.GetString("ConnectionErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00FFFF.
        /// </summary>
        internal static string CyanHexValue {
            get {
                return ResourceManager.GetString("CyanHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_Event.
        /// </summary>
        internal static string ErrorEvent {
            get {
                return ResourceManager.GetString("ErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Line.
        /// </summary>
        internal static string EventLine {
            get {
                return ResourceManager.GetString("EventLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFD700.
        /// </summary>
        internal static string GoldHexValue {
            get {
                return ResourceManager.GetString("GoldHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E0E0E0.
        /// </summary>
        internal static string GrayBackGroundHexValue {
            get {
                return ResourceManager.GetString("GrayBackGroundHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #808080.
        /// </summary>
        internal static string GrayHexValue {
            get {
                return ResourceManager.GetString("GrayHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #7CFC00.
        /// </summary>
        internal static string GreenHexValue {
            get {
                return ResourceManager.GetString("GreenHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import warning!.
        /// </summary>
        internal static string ImportWarning {
            get {
                return ResourceManager.GetString("ImportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime Green.
        /// </summary>
        internal static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #32CD32.
        /// </summary>
        internal static string LimeGreenHexValue {
            get {
                return ResourceManager.GetString("LimeGreenHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFA500.
        /// </summary>
        internal static string OrangeHexValue {
            get {
                return ResourceManager.GetString("OrangeHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF1493.
        /// </summary>
        internal static string PinkHexValue {
            get {
                return ResourceManager.GetString("PinkHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #800080.
        /// </summary>
        internal static string PurpleHexValue {
            get {
                return ResourceManager.GetString("PurpleHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF0000.
        /// </summary>
        internal static string RedHexValue {
            get {
                return ResourceManager.GetString("RedHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        internal static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files saved successfully in EDF format..
        /// </summary>
        internal static string SaveEDF {
            get {
                return ResourceManager.GetString("SaveEDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (s).
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string WhiteHexValue {
            get {
                return ResourceManager.GetString("WhiteHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFF00.
        /// </summary>
        internal static string YellowHexValue {
            get {
                return ResourceManager.GetString("YellowHexValue", resourceCulture);
            }
        }
    }
}
